//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OT.RentCoder.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_UserSkills
    {
        public int UserSkillID { get; set; }
        public int UserId { get; set; }
        public int SkillID { get; set; }
    
        public virtual OT_Skills OT_Skills { get; set; }
        public virtual OT_User OT_User { get; set; }
    }
}
