//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OT.RentCoder.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_UserProfile
    {
        public int ProfileID { get; set; }
        public string FullLegalName { get; set; }
        public int CountryID { get; set; }
        public string CityName { get; set; }
        public int TimeZoneID { get; set; }
        public int Citizenship { get; set; }
        public string Aboutme { get; set; }
        public string Skills { get; set; }
        public string ResumePath { get; set; }
        public string PersonalWebSiteURL { get; set; }
        public string LinkedinURL { get; set; }
        public string GithubUserName { get; set; }
        public string SampleCodePath { get; set; }
        public string WhatIsThisCodeAbout { get; set; }
        public Nullable<int> USStateID { get; set; }
        public Nullable<int> CharacterizesID { get; set; }
        public string AmazingApplication { get; set; }
        public string HowLongAvailable { get; set; }
        public string AvailableHoursPerWeek { get; set; }
        public string HowManyHoursWorkforRentCoder { get; set; }
        public string WhatDoYouLookForInACompany { get; set; }
        public string WhatTypesOfProjects { get; set; }
        public string QuestionsOrComments { get; set; }
        public bool IsAcceptTermsAndConditions { get; set; }
        public int UserId { get; set; }
    
        public virtual OT_Characterizes OT_Characterizes { get; set; }
        public virtual OT_Country OT_Country { get; set; }
        public virtual OT_TimeZone OT_TimeZone { get; set; }
        public virtual OT_USState OT_USState { get; set; }
        public virtual OT_User OT_User { get; set; }
    }
}
